# Generated by Django 5.0.6 on 2024-07-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_data",
            field=models.DateField(auto_now_add=True, verbose_name="Дата оплаты"),
        ),
    ]
