# Generated by Django 5.0.6 on 2024-07-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_payment_payment_link_payment_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Статус оплаты"
            ),
        ),
    ]
