# Generated by Django 5.0.6 on 2024-07-04 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_payment_payment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="payment_sum",
        ),
    ]
