# Generated by Django 5.0.6 on 2024-07-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video",
            field=models.URLField(
                blank=True,
                help_text="Введите ссылку на видео с уроком",
                null=True,
                verbose_name="Видеоурок",
            ),
        ),
    ]
