# Generated by Django 5.0.6 on 2024-07-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_alter_lesson_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="cost",
            field=models.PositiveIntegerField(
                default=10000, help_text="Укажите цену курса", verbose_name="Цена курса"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="cost",
            field=models.PositiveIntegerField(
                default=500, help_text="Укажите цену урока", verbose_name="Цена урока"
            ),
        ),
    ]
